site_name: Бази даних
site_description: Повний курс з баз даних з лекціями, лабораторними роботами та презентаціями.
site_author: Олександр Ройко
site_url: https://olroi421.github.io/course-bd/

# Repository
repo_name: olroi421/course-bd
repo_url: https://github.com/olroi421/course-bd
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2025 Олександр Ройко

theme:
  name: material
  language: uk
  icon:
    logo: fontawesome/solid/database
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.action.view
    - content.print

  palette:
    # Автоматична тема (за замовчуванням)
    - media: "(prefers-color-scheme)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-auto
        name: Перемкнути на світлу тему
    # Світла тема
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Перемкнути на темну тему
    # Темна тема
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Перемкнути на автоматичну тему

# Plugins
plugins:
  - search:
      lang: uk
  - mermaid2

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.keys
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - toc:
      permalink: true

# Navigation
nav:
  - Головна: index.md
  - Лекції:
      - lectures/index.md
      - "Лекція 1. Еволюція систем управління даними": lectures/lecture-01.md
      - "Лекція 2. Архітектура систем управління базами даних": lectures/lecture-02.md
      - "Лекція 3. Моделі представлення даних": lectures/lecture-03.md
      - "Лекція 4. Реляційна модель даних": lectures/lecture-04.md
      - "Лекція 5. Концептуальне моделювання предметних областей": lectures/lecture-05.md
      - "Лекція 6. Теорія нормалізації реляційних схем": lectures/lecture-06.md
      - "Лекція 7. Логічне та фізичне проектування": lectures/lecture-07.md
      - "Лекція 8. Обробка та оптимізація запитів": lectures/lecture-08.md
      - "Лекція 9. Управління транзакціями та паралельним доступом": lectures/lecture-09.md
      - "Лекція 10. Збережені процедури та активні бази даних": lectures/lecture-10.md
      - "Лекція 11. Теоретичні основи NoSQL систем": lectures/lecture-11.md
      - "Лекція 12. MongoDB: архітектура та модель даних": lectures/lecture-12.md
      - "Лекція 13. Проектування NoSQL схем": lectures/lecture-13.md
      - "Лекція 14. Elasticsearch та пошукові системи": lectures/lecture-14.md
      - "Лекція 15. Хмарні бази даних та Database-as-a-Service": lectures/lecture-15.md
      - "Лекція 16. Масштабування та розподілені архітектури": lectures/lecture-16.md
      - "Лекція 17. Безпека та адміністрування баз даних": lectures/lecture-17.md
      - "Лекція 18. Моніторинг продуктивності та налагодження": lectures/lecture-18.md

  - Лабораторні роботи:
      - labs/index.md
      - "Лабораторна робота 1. Робота з СУБД PostgreSQL та основи SQL": labs/lab-01.md
      - "Лабораторна робота 2. Створення складних SQL запитів": labs/lab-02.md
      - "Лабораторна робота 3. Модифікація даних та транзакції": labs/lab-03.md
  - Презентації:
      - presentations/index.md
      - "Еволюція систем управління даними": presentations/presentation-01.md
      - "Архітектура систем управління базами даних": presentations/presentation-02.md
      - "Моделі представлення даних": presentations/presentation-03.md
      - "Реляційна модель даних": presentations/presentation-04.md
      - "Концептуальне моделювання предметних областей": presentations/presentation-05.md
      - "Теорія нормалізації реляційних схем": presentations/presentation-06.md
      - "Логічне та фізичне проектування": presentations/presentation-07.md
      - "Обробка та оптимізація запитів": presentations/presentation-08.md
      - "Управління транзакціями та паралельним доступом": presentations/presentation-09.md
      - "Збережені процедури та активні бази даних": presentations/presentation-10.md
      - "Теоретичні основи NoSQL систем": presentations/presentation-11.md
      - "MongoDB: архітектура та модель даних": presentations/presentation-12.md
      - "Проектування NoSQL схем": presentations/presentation-13.md
      - "Elasticsearch та пошукові системи": presentations/presentation-14.md
      - "Хмарні бази даних та Database-as-a-Service": presentations/presentation-15.md
      - "Масштабування та розподілені архітектури": presentations/presentation-16.md
      - "Безпека та адміністрування баз даних": presentations/presentation-17.md
      - "Моніторинг продуктивності та налагодження": presentations/presentation-18.md

# Extra CSS
extra_css:
  - stylesheets/extra.css

# Extra JavaScript
extra_js:
  - javascripts/theme-persistence.js
  - javascripts/mermaid-zoom.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js
